files = [
    "atlas"
    "axes"
    "chain_in_chain"
    "dice_nofriction"
    # "dice_tiltedplane"
    "dice"
    "disconnected_bodies"
    "doublependulum_3d"
    # "doublependulum_disconnection"
    "doublependulum_urdf"
    "elliptic_joint"
    # "fourbar_disconnection"
    "inverted_pyramid_plane"
    "joint_force"
    "joint_torque"
    "n_fourbars"
    "n_pendulum"
    "nutation"
    "pendulum_forced"
    "pendulum"
    "planar_example"
    "scissor_lift"
    "slider_crank"
    "slider_crank3d"
    "wheel"
]

controlled = [
    # "doublependulum_disconnection"
    "joint_force"
    "joint_torque"
    "pendulum_forced"
    "nutation"
    # "fourbar_disconnection"
    "slider_crank"
]